### ISSUE TITLE
Misaligned absolute child in a fixed flex parent

### ISSUE THREAD

**Issue by JustOff** [MoonchildProductions/UXP#1007]
Steps to reproduce:
```css
parent {
  position: fixed;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 200px;
  height: 200px;
  background: yellow;
}

child {
  position: absolute;
  width: 100px;
  height: 100px;
  background: green;
}
```

See https://jsfiddle.net/4hgqp0bn/

Actual results:
Initially, the child element is centered around the top left corner.
If a page is resized (e.g. press F12), the positioning becomes correct (centered in the parent).
(Similar if using "flex-end"... but easy workaround: remove position: absolute;)

Expected results:
Correct position from the start.

See https://bugzilla.mozilla.org/show_bug.cgi?id=1386654.

In particular, this leads to incorrect display of the login form on [Firefox Send](https://send.firefox.com/).
