### ISSUE TITLE
Borders are visible in lightweight themes [PM28]

### ISSUE THREAD

**Issue by FranklinDM** [MoonchildProductions/UXP#713]
Borders should be hidden when using lightweight themes - this was the behavior in Pale Moon 27.
As reported on the forum:
https://forum.palemoon.org/viewtopic.php?f=3&t=19935&p=147714
https://forum.palemoon.org/viewtopic.php?f=3&t=19930

PM27 (global/toolbar.css)
```css
menubar:-moz-lwtheme,
toolbox:-moz-lwtheme,
toolbar:-moz-lwtheme {
  -moz-appearance: none;
  background: none;
  border-style: none;
}
````

PM28 (global/toolbar.css)
```css
menubar:-moz-lwtheme,
toolbox:-moz-lwtheme,
toolbar:-moz-lwtheme {
  -moz-appearance: none;
  background: none;
  border-color: transparent;
}
```
